### ISSUE TITLE
preserve מ:רווח לספר בתהלים in MAM-parsed-plus

### ISSUE THREAD

**Issue by bdenckla** [bdenckla/MAM-parsed#4]

**Comment by bdenckla** [comment]
@awes12, Psalms.json now has, at key "psalm_division_tmpls", the following value:

```json
      {
        "א": {
          "tmpl_name": "מ:רווח לספר בתהלים",
          "tmpl_args": [
            "ספר ראשון"
          ]
        },
        "מב": {
          "tmpl_name": "מ:רווח לספר בתהלים",
          "tmpl_args": [
            "ספר שני"
          ]
        },
        "עג": {
          "tmpl_name": "מ:רווח לספר בתהלים",
          "tmpl_args": [
            "ספר שלישי"
          ]
        },
        "צ": {
          "tmpl_name": "מ:רווח לספר בתהלים",
          "tmpl_args": [
            "ספר רביעי"
          ]
        },
        "קז": {
          "tmpl_name": "מ:רווח לספר בתהלים",
          "tmpl_args": [
            "ספר חמישי"
          ]
        }
      }
```

**Comment by bdenckla** [comment]
I got rid of `psalm_division_tmpls` in favor of using a new template, מ:רווח לספר בתהלים בפסק ראשון, in col C of the relevant row א.

**Comment by skadish1** [comment]
What's "בפסק ראשון"? Write what you mean in English and I'll try to suggest
a translation.

**Comment by awes12** [comment]
> What's "בפסק ראשון"? Write what you mean in English and I'll try to suggest a translation.

It means "in the first verse" (referring to the first verse in that psalm). 

Btw, can I suggest a change to something like מ:רווח לספר חדש בתהלים בפסק ראשון to make the usage clear ("an empty space for a new book in tehillim in the first verse")? Maybe you can also add באמצע תהילים (meaning "within psalms").

**Comment by bdenckla** [comment]
@skadish1: Yes as @awes12 said, I meant "בפסק ראשון" to mean "in the first verse", though:

- Now I have some doubts about my Hebrew, wondering if I should have written ראשון with a ה prefix, i.e. wondering whether I should have written הראשון.
- Now I notice I left out the *vav shuruq*, i.e. I should have written בפסוק not בפסק.

As a reminder, the idea (that I fear I somewhat botched) was to create "first verse" versions of the following two existing templates:

- מ:רווח בתרי עשר
- מ:רווח לספר בתהלים

So, @awes12, though I see merit in your suggestions:

- מ:רווח לספר חדש בתהלים בפסק ראשון
- מ:רווח לספר חדש באמצע תהילים בפסק ראשון

I think I should try to restrict myself to adding a phrase to the existing templates. Perhaps that phrase should have been בפסוק הראשון not בפסק ראשון though.

**Comment by skadish1** [comment]
Yes, it should read בפסוק הראשון.

**Comment by bdenckla** [comment]
> Yes, it should read בפסוק הראשון.

Okay I've created a spin-off issue for this, issue #8.

**Comment by bdenckla** [comment]
The fixes to the template names are now complete. See #8.
