### ISSUE TITLE
17 suspiciously-blank cells in col C of "plus"

### ISSUE THREAD

**Issue by bdenckla** [bdenckla/MAM-parsed#5]
This issue is a spin-off of #2.

**Comment by awes12** [comment]
It seems that {מ:רווח בתרי עשר} is also missing. Besides that, there's שמות לד ז,ח

**Comment by bdenckla** [comment]
I left out מ:רווח בתרי עשר from MAM-parsed-plus intentionally, since it seemed easy for a MAM-using application to know when a book of "the 12" is starting. Nonetheless, if you'd like to see it included, please open up a separate issue for that, and I'll consider it.

In answer to your question, my plan would probably be to add מ:רווח בתרי עשר at the top level of each of the 12 the books in question. Analogous to what I did with Psalms. There is no row (pseudo-verse) zero in MAM-parsed-plus, nor do I plan to add one. So it can't go there.

In MAM-parsed-plain, both מ:רווח templates (Psalms and "the 12") are present in row (pseudo-verse) zero. Today.

**Comment by bdenckla** [comment]
@awes12 Can you elaborate on your concern about שמות לד ז,ח (perhaps in a separate GitHub issue)?

**Comment by skadish1** [comment]
Hi Ben,
Overall, I agree with what this guy says. These templates contain masoretic
information. The line divisions between the Twelve Prophets are different
than between books.
If there is a way to do it, I think the best thing would be to include all
of the chapter-page information at Wikisource in the programmed MAM, with
options to leave it out for purposes that do not require it.
Avi

**Comment by bdenckla** [comment]
I am beginning to "see the light." By "see the light" I mean:

- I am beginning to see the relationship between the suspiciously blank cells in column C and the lack of Psalms and "the 12" divisions. Namely, that:
   - These divisions used to "live" in cells in column C (of א rows not zero rows!)
   - These divisions were recently auto-edited away from those cells (good! they don't belong there in א rows. but they do belong somewhere)
   - this left n-1 of those cells empty (4 for Psalms, 11 for "the 12")
- See the relationship between the suspiciously blank cells in column C and שמות לד ז,ח. Namely, that שמות לד ז,ח contain two of those 17 blank cells.

**Comment by bdenckla** [comment]
Because I have now fixed #7, the count is down from 17 to 15 suspiciously-blank cells.

**Comment by bdenckla** [comment]
I have implemented one of the two new templates I proposed above: מ:רווח לספר בתהלים בפסק ראשון. This brings the number of blank cells in col C down from 15 to 11.

Going along with this change, I have removed the `psalm_division_tmpls` header.

**Comment by bdenckla** [comment]
I have implemented the second of the two new templates I proposed above: מ:רווח בתרי עשר בפסק ראשון. This brings the number of blank cells in col C down from 11 to 9. So I'm going to close this issue.

**Comment by awes12** [comment]
Should the first sefarim in Psalms and the Trei Asar have the space template? It seems that the רווח is a space between intra-sefer sefarim, and therefore shouldn't be in the first one (like in Hoshea and Psalms 1).

**Comment by bdenckla** [comment]
Thanks @awes12 that is a good point. I will open up a separate issue to track this question, the question of whether the first of n divisions (for n=12 or n=5) should be encoded differently.
