### ISSUE TITLE
preserve מ:רווח בתרי עשר in MAM-parsed-plus

### ISSUE THREAD

**Issue by awes12** [bdenckla/MAM-parsed#6]
If the logic of leaving this out is that it is unneeded, you can say the same with מ:ספר חדש. I think that it makes sense to include it at the start of the sefer, to add a פפ like with shmuel bet, or to add a new template called מ:חלק חדש בספר or something like that and use it for all sub-sections in sefarim.

**Comment by skadish1** [comment]
All of these templates are to let the publisher choose what to do at
various types of "beginnings." For some of them, there are different
masoretic practices to take into account.
BTW, Melakhim Bet doesn't - and should not have! a פפ.
Avi

**Comment by awes12** [comment]
Ah, you're right, I meant Shmuel Bet (assumed it was the same for Melachim, but it's מ:אין פרשה בתחילת פרק there).

**Comment by bdenckla** [comment]
The מ:רווח בתרי עשר template calls are now preserved in spirit though not in letter.

They are preserved via 12 calls to the new template מ:רווח בתרי עשר בפסק ראשון. (It has the same name as the מ:רווח בתרי עשר but with בפסק ראשון added.)

So, I will close this issue.

**Comment by bdenckla** [comment]
The names of this template and its Tehillim "twin" have been fixed a little. See #8.
