### ISSUE TITLE
No spaces in pesukim שמות לד ז and ח

### ISSUE THREAD

**Issue by awes12** [bdenckla/MAM-parsed#7]
As you can see in the image below, there are no spaces in column C for these 2 pesukim. As far as I know, there shouldn't be a reason for this (but if it's intentional, please let me know why).
![image](https://github.com/bdenckla/MAM-parsed/assets/48301725/b8e4285d-44d9-4e29-b016-b5fd274550a4)

**Comment by skadish1** [comment]
That is indeed weird.
They should be there.

**Comment by bdenckla** [comment]
To my amusement, I just discovered, in a private GitHub repository of mine, an issue I created about 5 months ago entitled "investigate empty CP in Ex 34:7 & 34:8".

**Comment by bdenckla** [comment]
Fixed in https://github.com/bdenckla/MAM-parsed/commit/9d11b8745d9ae087884a5559960943786d25f782.
