### ISSUE TITLE
Distinctly encode the first division of Psalms and the Trei Asar?

### ISSUE THREAD

**Issue by bdenckla** [bdenckla/MAM-parsed#9]
Should the first sefarim in Psalms and the Trei Asar have the space template? It seems that the רווח is a space between intra-sefer sefarim, and therefore shouldn't be in the first one (like in Hoshea and Psalms 1).

_Originally posted by @awes12 in https://github.com/bdenckla/MAM-parsed/issues/5#issuecomment-1926908547_

**Comment by bdenckla** [comment]
This is a good point/question.

- Some editions will want to do something at the start of all 12 parts ("sub-books"). For instance, Wikisource uses this template to generate a title for the part ("sub-book").
- Some editions will want to do something only at the start of all 11 non-initial parts ("sub-books").
- Some editions will want to do both (something for all 12, and something different for all 11).

(Same idea applies to the divisions of the Psalms of course, i.e. all 5 divisions versus the 4 non-initial ones.)

We had a similar problem with *aliyot*, and the way we solved it was to add the following optional argument to the מ:פסוק template call in the first *aliyah*, identifying it as the first *aliyah*:

עלייה ראשונה=כן

E.g.

{{מ:פסוק|במדבר|א|א|סדר=א|עלייה='''במדבר'''|עלייה ראשונה=כן}}

versus a non-first *aliyah* (in this case עלייה שלישי):

{{מ:פסוק|במדבר|ב|א|סדר=ב|עלייה=שלישי}}

For the 12 divisions of תרי עשר and the 5 divisions of תהלים, we might just add a non-optional final argument representing which number (1..N) division this is, e.g. for תרי עשר:

{{מ:רווח בתרי עשר|הושע|1}}
{{מ:רווח בתרי עשר|יואל|2}}
...

(Of course, if preferred, this could use Hebrew numerals א, ב, ... instead of Western Arabic numerals 1, 2, ....)

Of course, many MAM-using applications can just do this counting themselves based on today's encoding, but in general we try to encode things so that the MAM-using application can be as stateless as possible, for common use cases.

Supplying this numbering does assume that the MAM-using application have some conditional capability, to do something like "if arg2 == 1 {...} else {...}".

@skadish1 what do you think?

**Comment by awes12** [comment]
Any update on this?

**Comment by bdenckla** [comment]
The proposal is to add a final, numeric "counter" argument to the following two recently-added templates:

* מ:רווח בתרי עשר בפסוק הראשון
* מ:רווח לספר בתהלים בפסוק הראשון

For example, a counter of 1 (one) would be added to the following template "calls":

* {{מ:רווח לספר בתהלים בפסוק הראשון|ספר ראשון|1}}
* {{מ:רווח בתרי עשר בפסוק הראשון|הושע|1}}

@skadish1 Let me know if you feel differently, but my inclination is to NOT add these arguments.

* The first division of Psalms is unlikely to be ever called anything other than "ספר ראשון"
* The first division (sub-book) of the 12 minor prophets is unlikely to be ever called anything other than "הושע"

So, the use case of testing whether the counter equals 1 (one) is unlikely to provide any value beyond what can already be done by testing whether the division is "ספר ראשון" or "הושע" respectively.

And there was no other currently-envisioned use case for this counter, other than testing for "equals 1."
